M48
; DRILL file {KiCad 9.0.6} date 2025-12-22T18:43:20-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-22T18:43:20-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X149.26Y-72.475
X149.26Y-91.588
T2
X104.5Y-101.114
X104.5Y-134.5
X173.446Y-101.114
X173.446Y-134.5
M30
